# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeReduxExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeReduxExample
  pod 'Firebase/AdMob'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

end

