export const INITIALIZED = 'INITIALIZED';
export const ROOT_CHANGED = 'ROOT_CHANGED';

export const REQUEST_KEYPAIRS = 'REQUEST_KEYPAIRS';
export const RECEIVE_KEYPAIRS = 'RECEIVE_KEYPAIRS';

export const REQUEST_PAGEN_KEYPAIRS = 'REQUEST_PAGEN_KEYPAIRS';
export const RECEIVE_PAGEN_KEYPAIRS = 'RECEIVE_PAGEN_KEYPAIRS';
